import { DownOutlined } from "@ant-design/icons";
import { useCurrentUser } from "@/utils/user";
import { MenuProps, Space, message } from "antd";
import { Layout as AntdLayout, Dropdown, Menu } from "antd";
import Head from "next/head";
import Image from "next/image";
import { useRouter } from "next/router";
import React, { useEffect, useState } from "react";
import styles from "./index.module.css";
import { logout } from "@/api/user";
import Link from "next/link";

const { Header, Content, Sider } = AntdLayout;

const ITEMS = [
  {
    // icon: React.createElement(icon),
    label: "Book Management",
    key: "book",

    children: [
      { label: "Book List", key: "/book" },
      { label: "Add Book", key: "/book/add" },
    ],
  },
  {
    // icon: React.createElement(icon),
    label: "Borrow History",
    key: "borrow",

    children: [
      { label: "Borrow List", key: "/borrow" },
      { label: "Borrow Add", key: "/borrow/add" },
    ],
  },
  {
    // icon: React.createElement(icon),
    label: "Category Management",
    key: "category",

    children: [
      { label: "Category List", key: "/category" },
      { label: "Add Category", key: "/category/add" },
    ],
  },
  {
    // icon: React.createElement(icon),
    label: "User Management",
    key: "user",

    children: [
      { label: "User List", key: "/user" },
      { label: "Add User", key: "/user/add" },
    ],
  },
];

export function Layout({ children }:{ children: React.ReactNode }) {
  const router = useRouter();
  //const [user, setUser] = useState({info: {nickName: ""}});
  const user = useCurrentUser();
  //console.log(user)
  //console.log(user._id);
  const handleMenuClick : MenuProps ["onClick"] = ({ key }) => {
    router.push(key);
  };

  const handleChangeMenu: MenuProps["onClick"] = (e) => {
    router.push(e.key);
  };

  const USER_ITEMS: MenuProps["items"] = [
    {
      label: <Link href={`/user/edit/${user?.info?._id}`}>User Info</Link>,
      key: "1",
    },
    {
      label: (
        <span
          onClick={async () => {
            await logout();
            localStorage.removeItem("user");
            message.success("Logout Success");
            router.push("/login");
          }}
        >
          Logout
        </span>
      ),
      key: "2",
    },
  ];

  // useEffect(() => {
  //   if (typeof window !== "undefined") {
  //     const userStorage = localStorage?.getItem("user");
  //     if (userStorage) {
  //       setUser(JSON.parse(userStorage));
  //     }
  //   }
  // },[]);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <AntdLayout>
          <Header className={styles.header}>
            <Image
              src="/next.svg"
              width={30}
              height={30}
              alt="logo"
              className={styles.logo}
            />
            Book Management System
            <span className={styles.user}>
              <Dropdown menu={{ items: USER_ITEMS }}>
                <a onClick={(e) => e.preventDefault()}>
                  <Space>
                    {user?.info?.nickName ? user?.info?.nickName : "username"}
                    <DownOutlined />
                  </Space>
                </a>
              </Dropdown>
            </span>
          </Header>
          <AntdLayout className={styles.sectionInner}>
            <Sider width={200}>
              <Menu
                mode="inline"
                defaultSelectedKeys={["/book"]}
                defaultOpenKeys={["book"]}
                selectedKeys={[router.pathname]}
                style={{ height: "100%", borderRight: 0 }}
                items={ITEMS}
                onClick={handleMenuClick}
              />
            </Sider>
            <AntdLayout className={styles.sectionContent}>
              <Content className={styles.content}>{children}</Content>
            </AntdLayout>
          </AntdLayout>
        </AntdLayout>
      </main>
    </>
  );
}
